### ISSUE TITLE
Vertical alignment for embeds

### ISSUE THREAD

**Issue by stdword** [sethyuan/logseq-plugin-another-embed#21]
Hello!
I use this CSS to make the size of embedded text block vertically the same as simple text block:

```css
.embed-block > div {
    padding-left: 0px;
    padding-bottom: 0px;
    padding-top: 0px;
}
```

## Comparison
<img width="150px" src="https://github.com/sethyuan/logseq-plugin-another-embed/assets/1984175/106cf18f-d278-49a1-a2da-5e71464c6848"/>

Probably it is nice to add it to this plugin?
